name = "evergreen-api"
main = "src/index.js"
workers_dev = true
compatibility_date = "2022-05-30"
account_id = "3f3a99ad15db52fca58be0e080912991"
vars = { ENVIRONMENT = "dev" }

[env.staging]
name = "evergreen-api-staging"
vars = { ENVIRONMENT = "staging" }
# routes = [
#     "evergreen-api-staging.stealthpuppy.workers.dev/*"
# ]

[env.production]
name = "evergreen-api"
vars = { ENVIRONMENT = "production" }
# routes = [
#   "evergreen-api.stealthpuppy.workers.dev/*"
# ]

kv_namespaces = [
    { binding = "EVERGREEN", id = "037069e7da3e4944be2cbc97c92409a5" }
]
