name = "evergreen-api"
#type = "webpack"
main = "index.js"
workers_dev = true
# node_compat = true
compatibility_date = "2022-05-30"
#webpack_config = "webpack.config.js"
#account_id = "_your_account_id_"
#zone_id = "_your_zone_id_"

kv_namespaces = [
    { binding = "EVERGREEN", id = "037069e7da3e4944be2cbc97c92409a5" }
]

# [env.staging]
# kv_namespaces = [
#     { binding = "EVERGREEN", preview_id = "cbd95467b293457c87a8c6233307ae0f" }
# ]

# [env.production]
# kv_namespaces = [
#     { binding = "EVERGREEN", id = "037069e7da3e4944be2cbc97c92409a5" }
# ]
