name = "evergreen-api"
main = "index.js"
workers_dev = true
compatibility_date = "2022-05-30"
account_id = "3f3a99ad15db52fca58be0e080912991"
vars = { ENVIRONMENT = "production" }
kv_namespaces = [
    { binding = "EVERGREEN", id = "037069e7da3e4944be2cbc97c92409a5", preview_id = "037069e7da3e4944be2cbc97c92409a5" }
]

[env.production]
name = "evergreen-api"
vars = { ENVIRONMENT = "production" }
kv_namespaces = [
    { binding = "EVERGREEN", id = "037069e7da3e4944be2cbc97c92409a5", preview_id = "037069e7da3e4944be2cbc97c92409a5" }
]

[[env.production.r2_buckets]]
binding = "LOGS_BUCKET"
bucket_name = "evergreen-api"
preview_bucket_name = "evergreen-api-test"

[env.staging]
name = "evergreen-api-staging"
vars = { ENVIRONMENT = "staging" }
kv_namespaces = [
    { binding = "EVERGREEN", id = "037069e7da3e4944be2cbc97c92409a5", preview_id = "037069e7da3e4944be2cbc97c92409a5" }
]

[[env.staging.r2_buckets]]
binding = "LOGS_BUCKET"
bucket_name = "evergreen-api"
preview_bucket_name = "evergreen-api-test"
