name: Deploy-Worker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-worker.yml"
      - "src/index.js"
      - "wrangler.toml"
      - "package.json"
      - "package-lock.json"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - uses: actions/checkout@v3

      - name: npm install
        id: install
        shell: bash
        run: |
          cd "${{ github.workspace }}"
          npm install

      - name: wrangler publish production
        uses: cloudflare/wrangler-action@3.0.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: publish  --env production
